name: Run Robot Tests Daily

on:
  schedule:
    - cron: '0 3 * * *'  # Executa todos os dias às 03:00 UTC
  workflow_dispatch:     # Permite rodar manualmente também

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório
        uses: actions/checkout@v3

      - name: Configurar PYTHONPATH
        run: echo "PYTHONPATH=${GITHUB_WORKSPACE}" >> $GITHUB_ENV

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências do sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y \
           wget \
           unzip \
           xvfb \
           libglib2.0-0 \
           libnss3 \
           libfontconfig1 \
           libxss1 \
           libasound2t64

      - name: Instalar dependências Python
        run: pip install -r requirements.txt

      - name: Instalar Google Chrome (via apt)
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Rodar testes Robot
        run: |
          Xvfb :99 -ac &
          export DISPLAY=:99
          robot TestCases

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Robot Framework Reports
          path: |
            output.xml
            log.html
            report.html
